
# eq_fct_type's are defined in eq_fct_code.h

eq_conf:

oper_uid:   -1
oper_gid:  1432 
xpert_uid:  0
xpert_gid:   6194
ring_buffer:  500000
memory_buffer:  500

eq_fct_name:  "NODENAME._SVR"
eq_fct_type:  1
{
SVR.NAME:   "NODENAME._SVR"
STS.ONLINE:   1
FCT_CODE:   1
SVR.RATE:   1  0  0  0
SVR.DESC:   ""
SVR.PROGRAMMER:   "ChimeraTK Developer"
SVR.STORE.RATE:   60
SVR.STORE.AUTO:   10
SVR.HOST_NAME:    "localhost"
SVR.RPC_NUMBER: 610498009
SVR.FACILITY: "TEST.DOOCS"
SVR.NO_NAME_SERVICE_REGISTRATION: 1
SVR.DEVICE: "LOCALHOST_610498009"
SVR.SPR:    0
}
